### PR TITLE
Julia 1.0 compatibility, dropping 0.6

### PR DESCRIPTION
**Pull request by schmrlng**
Mostly just find/replace stuff; I didn't think carefully about whether any of the logic should be updated to better fit julia 1.0 features.

This PR will only work for julia 0.7+. To maintain 0.6 compatibility, I propose that a release be tagged for the current state of this repo (e.g., v0.2.0), and then another release be tagged after this PR is accepted/merged (e.g., v1.0.0).

### CODE REVIEW

**Comment by wildart** [comment]
LGTM. As soon as I create necessary tags. I'll merge it.

**Comment by schmrlng** [comment]
Great, thanks. I'm also going to push a commit here shortly that loosens a lot of the `Matrix`/`Vector` type restrictions to `AbstracMatrix`/`AbstractVector` so that, e.g., `ReshapedArray`s/`ReinterpretArray`s produced by `reinterpret`ing `Vector`s of `SVector`s will also work. Please let me know if you'd instead prefer that change in a separate PR for discussion.

**Comment by schmrlng** [comment]
Bump, I think this is good to go -- thanks!

**Comment by schmrlng** [comment]
Revisiting this I think attobot now only works for tagging packages on julia 0.6 and earlier (which we may still want to do to tag the current state of this repo as v0.2.0).

After this PR is merged I think that we can just follow the instructions here to tag and release a 1.0-compatible version: https://github.com/JuliaRegistries/Registrator.jl. Theoretically, after merging this PR, to release a new version (I've put 1.0.0 in the Project.toml included in this PR; let me know if you'd prefer a different number) all you'll have to do is install Registrator and comment "@JuliaRegistrator register()" on the PR merge commit.

**Comment by wildart** [comment]
@JuliaRegistrator register()

**Pull request merged**
