### PR TITLE
fixes warning for versions 0.4.0

### PR DESCRIPTION
**Pull request by joclement**
I saw that someone already wanted to fix the deprecated warnings, but didn't use Compat. I did it with that. I hope it is correct :) 

I've built and tested it with your testfiles.

### CODE REVIEW

**Comment by joclement** [comment]
the only build fail seems to be related to some fault in Homebrew

**Comment by tkelman** [comment]
Add `Compat` to `REQUIRE`, and change `julia 0.3-` to `julia 0.3` while you're at it

**Comment by joclement** [comment]
do you think we can do something about the build fail on mac os with the julia nightly build?

**Comment by wildart** [comment]
not really, it looks like [`Homebrew.jl` does not agree with julia master branch](https://github.com/JuliaLang/Homebrew.jl/issues/98).

**Pull request merged**
